# Generated by Django 2.0.7 on 2018-11-24 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupname', models.CharField(default='NA', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photoid', models.IntegerField()),
                ('owner', models.CharField(max_length=20)),
                ('photourl', models.CharField(max_length=200)),
                ('title', models.CharField(default='No Title', max_length=200)),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gname', to='photofy.Group')),
            ],
        ),
    ]
