# Generated by Django 2.0.7 on 2018-11-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photos',
            name='photourl',
            field=models.URLField(),
        ),
    ]
