# Generated by Django 2.0.7 on 2018-11-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofy', '0002_auto_20181125_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='photos',
            name='user',
            field=models.CharField(default='NA', max_length=30),
        ),
    ]
