# Generated by Django 2.0.7 on 2018-11-26 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('photofy', '0004_auto_20181126_1749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='user',
        ),
        migrations.AddField(
            model_name='photos',
            name='user_owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
