# Generated by Django 2.0.7 on 2018-11-26 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photofy', '0005_auto_20181126_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photos',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='photos',
            name='photoid',
        ),
    ]
