# Generated by Django 2.0.7 on 2018-12-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photofy', '0006_auto_20181126_1803'),
    ]

    operations = [
        migrations.CreateModel(
            name='CeleryData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('celeryid', models.CharField(max_length=100)),
            ],
        ),
    ]
